version: '4'

services:
  moodle_db:
    image: postgres:14.5-alpine 
    ports:
      - '8082:8082'
    volumes:
      - './data/db:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  moodle:
    image: ellakcy/moodle:postgresql_apache_lts
    volumes:
      - './data/moodle/data:/var/moodledata'
      - './data/moodle/www:/var/www/html'
    ports:
      - '8080:80'
    links:
      - moodle_db
    environment:
      MOODLE_URL: http://localhost:8080
      MOODLE_ADMIN: admin
      MOODLE_ADMIN_PASSWORD: admin
      MOODLE_ADMIN_EMAIL: admin@ontario.ca
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_USER: user
      MOODLE_DB_PASSWORD: password
      MOODLE_DB_NAME: db
