version: '2'
services:
  postgres:
    image: docker.io/bitnami/postgresql:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_USER=bn_moodle
      - POSTGRES_DATABASE=bitnami_moodle
      - POSTGRES_CHARACTER_SET=utf8mb4
      - POSTGRES_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'postgres_data:/bitnami/postgres'
  moodle:
    image: docker.io/bitnami/moodle:4
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=postgres
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local