version: '2'

services:

 nginx:
   image: nginx:alpine
   ports:
     - '8082:8082'
   volumes:
     - './conf/nginx.conf:/etc/nginx/nginx.conf:ro'
     - './logs/:/var/log/nginx'
   links:
     - 'moodle'
   volumes_from:
     - 'moodle'

 moodle_db:
  image: postgres:9-alpine
  volumes:
    - './data/db:/var/lib/postgresql/data'
    - './data/moodle/www:/var/www/html'
  environment:
    POSTGRES_DB: 'db'
    POSTGRES_USER: 'admin'
    POSTGRES_PASSWORD: 'admin'

 moodle:
    image: ellakcy/moodle:postgresql_fpm_alpine_202207092031
    volumes:
      - './data/moodle:/var/moodledata'
    links:
      - 'moodle_db'
    environment:
      MOODLE_URL: localhost/
      MOODLE_ADMIN: admin
      MOODLE_ADMIN_PASSWORD: admin
      MOODLE_ADMIN_EMAIL: admin@admin.ca
      MOODLE_DB_HOST: 'moodle_db'
      MOODLE_DB_USER: admin
      MOODLE_DB_PASSWORD: admin
