version: '2'

services:

 nginx:
   image: nginx:alpine
   ports:
     - '8082:8082'
   volumes:
     - './conf/nginx.conf:/etc/nginx/nginx.conf:ro'
     - './logs/:/var/log/nginx'
   links:
     - 'moodle'
   volumes_from:
     - 'moodle'

 moodle_db:
  image: postgres:alpine
  volumes:
    - './data/db:/var/lib/postgresql/data'
    - './data/moodle/www:/var/www/html'
  environment:
    POSTGRES_DB: 'db'
    POSTGRES_USER: 'user'
    POSTGRES_PASSWORD: 'password'

 moodle:
    image: ellakcy/moodle:postgresql_fpm_alpine
    volumes:
      - './data/moodle:/var/moodledata'
    links:
      - 'moodle_db'
    environment:
      MOODLE_URL: localhost:8080
      MOODLE_ADMIN: admin
      MOODLE_ADMIN_PASSWORD: password
      MOODLE_ADMIN_EMAIL: 'admin@admin.com'
      MOODLE_DB_HOST: 'moodle_db'
      MOODLE_DB_USER: user
      MOODLE_DB_PASSWORD: passowrd
      MOODLE_DB_NAME: db
      #MOODLE_REVERSE_LB: $MOODLE_REVERSE_LB
      #MOODLE_SSL: $MOODLE_SSL
      #MOODLE_EMAIL_TYPE_QMAIL: $MOODLE_EMAIL_TYPE_QMAIL
      #MOODLE_EMAIL_HOST: $MOODLE_EMAIL_HOST